# Generated by Django 3.2.4 on 2021-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_resume_name'),
        ),
    ]
