# Generated by Django 3.2.4 on 2021-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0002_resume_unique_resume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
